// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Source = { id: number, name: string, url: string, last_pub: string, last_poll: string | null, ttl: number | null, favorite: boolean, created_at: string, updated_at: string, };
