// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tag = { name: string, background_color: string | null, text_color: string | null, border_color: string | null, created_at: string, updated_at: string, };
