[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
freya = { version = "0.4.0", features = ["router", "query"] }
ureq = { version = "3.3.0", features = ["json"] }
tokio = { workspace = true, features = ["sync", "fs"] }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
serde_json.workspace = true
blocking = "1.6.2"
anyhow = "1.0.103"
rustc-hash.workspace = true
